name: Keep Streamlit App Awake

on:
  schedule:
    # Runs every second day at midnight UTC
    - cron: "0 0 */2 * *"
  workflow_dispatch: # Allows you to run it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit URL
        run: curl -s "https://realtimefrauddetection.streamlit.app/" > /dev/null
